version: '3.8'
services:
  database:
    image: mysql:8.0.34-debian
    container_name: database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - .\.docker\mysql:/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: swimming-pool
      TZ: Asia/Ho_Chi_Minh
  database-admin:
    image: phpmyadmin:5.2.1-apache
    container_name: mysql-admin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      PMA_HOST: database
    ports:
      - "80:80"
    depends_on:
      - database