server:
  shutdown: graceful
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 5MB
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
  datasource:
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swimming-pool?createDatabaseIfNotExist=true
    hikari:
      auto-commit: false
      connection-timeout: 10000
      maximum-pool-size: 10
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  messages:
    basename: message
    encoding: UTF-8
    use-code-as-default-message: true

# firebase
firebase:
  location: firebase.json
  bucket: swimming-pool-27ad5.appspot.com

# paypal api
paypal:
  client-id: ${paypal.client-id}
  client-secret: ${paypal.client-secret}
  mode: sandbox