server:
  shutdown: graceful
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 5MB
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
  datasource:
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swimming-pool?createDatabaseIfNotExist=true
    hikari:
      auto-commit: false
      connection-timeout: 10000
      maximum-pool-size: 10
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      repositories:
        enabled: false
  main:
    allow-bean-definition-overriding: true
logging:
  file:
    path: logs/swimming-pool.log
# firebase
firebase:
  enable: true
  location: firebase.json
  bucket: swimming-pool-27ad5.appspot.com
  urlImage: 'https://firebasestorage.googleapis.com/v0/b/{0}/o/{1}?alt=media'

# paypal api
paypal:
  client-id: ${paypal.client-id}
  client-secret: ${paypal.client-secret}
  mode: sandbox

# cache
cache:
  enable: true
  host: localhost
  port: 6379
  password: ${REDIS_PASSWORD}
  properties:
    - name: ACTIVE_POOL
      ttl: 1440